Seed: 1
Initial POI Locations: null
Initial Agent Positions: null
Number of Agents: 1
Number of POIs: 1
World Width: 30
World Length: 30
Coupling: 1
Observation Radius: 3.0
Minimum Distance: 1.0
Steps: 40
Epochs: 1000
